<a href="https://colab.research.google.com/github/tracynuwagaba/Numpy_projects/blob/main/PythonForDataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Initializing Numpy Arrays


In [ ]:
a = [1, 2, 3, 4]  # normal python list
numpy_a = np.array([1, 2, 3, 4], dtype='int16') # numpy 1d array

In [ ]:
# numpy 2d array
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])

In [ ]:
# Get Dimension
# a.ndim
b.ndim

2

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
print(b.dtype)

# Get Size
print(b.nbytes)

float64
48


# More types of NumPy initializations

In [ ]:
# All 0s matrix
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Matrix filled with any number
np.full((5,2), 8)

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

In [ ]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Random decimal numbers between 0-10
np.random.rand(4,2) * 10

array([[6.30310879, 4.93529009],
       [1.96114612, 2.3216467 ],
       [8.16185109, 7.99418753],
       [5.51555327, 7.61058689]])

In [ ]:
# Copying in numpy
a = np.array([1,2,3])
b = a.copy() # REMEMBER TO DO THIS. Otherwise, when b is mutated, a also changes

b[1] = 100
print(a)
print(b)

[1 2 3]
[  1 100   3]


#Numpy Indexing and Accessing Elements

In [ ]:
python_list = [
    ['apple', 'orange', 'banana'], 
    ['panda', 2, 100]]
python_list[1][2]

100

In [ ]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
a.shape

(2, 7)

In [ ]:
# Get a specific element [row, col]
# With slicing - [row_start:row_end, col_start:col_end]
# Can leave out row_start / col_start if 0
a[:2,:-2]

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12]])

In [ ]:
# Get a specific row 
row = a[0, :]
print(row)

# Get a specific column
col = a[:, 4]
print(col)

[1 2 3 4 5 6 7]
[ 5 12]


In [ ]:
# Modify array
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
# Example of indexing into 3D array

c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
  ])
# print(c)

# access 1st row, 1st col, 0th value
print(c[1, 1, 0])

7


# Numpy Shape-shifting

In [ ]:
# Concatenating arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((4,5))
h2 = np.full((4,2), 2)

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 1., 2., 2.]])

In [ ]:
# Reshape array
a = np.full((4, 8), 3)
print(a)

a_flat = a.flatten()
print(a_flat)

# Reshap a_flat to a rectangle matrix
b = np.reshape(a_flat, (2, 16))
print(b)

[[3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]


# Numpy Math & Broadcasting

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# Add value to all elements at once
print(a + 7)

[ 8  9 10 11]


In [ ]:
# Multiply all elements in a by value
print(a * 3)

[ 3  6  9 12]


In [ ]:
# Divide all elements in a by value
print(a / 2)

[0.5 1.  1.5 2. ]


In [ ]:
# Add 2 arrays together
b = np.array([4, 5, 6, 7]) # Needs to be the same shape! 

print(a + b)

[ 5  7  9 11]


In [ ]:
# Multiply 2 arrays together
print(a * b) # Needs to be the same shape!

[ 4 10 18 28]


In [ ]:
# Take the sin / cos of arrays
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
np.sin(a * b)

array([-0.7568025 , -0.54402111, -0.75098725,  0.27090579])

In [ ]:
# Perform linear algebra operations

# shape (2, 2)
a = np.array([
    [1, 2], 
    [2, 3]
])

# shape (3, 2)
b = np.array([
    [1, 2], 
    [2, 3],
    [3, 3]
])

# Error!
c = np.matmul(a, b)

ValueError: ignored

In [ ]:
c = np.matmul(a, b.transpose()) # (2, 2) x (2, 3) => (2, 3)
print(c)

[[ 5  8  9]
 [ 8 13 15]]


# Load data from file into Numpy

In [ ]:
filedata = np.genfromtxt('./sample_data/california_housing_train.csv', delimiter=',', skip_header=1)

print(filedata.shape)

(17000, 9)


In [ ]:
total_rooms = filedata[:, 3] 
total_rooms.shape

(17000,)

In [ ]:
print(min(total_rooms))
print(max(total_rooms))

2.0
37937.0


In [ ]:
# concatenate a new column to existing data
num_persons_living = np.full((17000, 1), 4)

filedata = np.hstack((filedata, num_persons_living))
print(filedata.shape)

(17000, 10)
